ALTER TABLE API_PEN_REPLICATION.PEN_DEMOG_TX
    MODIFY (
        TX_TYPE VARCHAR2(6),
        TX_STATUS VARCHAR2(6)
        );
ALTER TABLE API_PEN_REPLICATION.PEN_TWINS_TX
    MODIFY (
        TX_TYPE VARCHAR2(6),
        TX_STATUS VARCHAR2(6)
        );
