CREATE TABLE SAGA
(
    SAGA_ID     RAW(16)                             NOT NULL,
    SAGA_NAME   VARCHAR2(50)                        NOT NULL,
    SAGA_STATE  VARCHAR2(100)                       NOT NULL,
    PAYLOAD     BLOB                                NOT NULL,
    STATUS      VARCHAR2(20)                        NOT NULL,
    CREATE_USER VARCHAR2(32)                        NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER VARCHAR2(32)                        NOT NULL,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SAGA_PK PRIMARY KEY (SAGA_ID)
) TABLESPACE API_PEN_BLOB_DATA;
CREATE INDEX SAGA_STATUS_IDX ON SAGA (STATUS) TABLESPACE API_PEN_IDX;

CREATE TABLE SAGA_EVENT_STATES
(
    SAGA_EVENT_ID       RAW(16)                             NOT NULL,
    SAGA_ID             RAW(16)                             NOT NULL,
    SAGA_EVENT_STATE    VARCHAR2(100)                       NOT NULL,
    SAGA_EVENT_OUTCOME  VARCHAR2(100)                       NOT NULL,
    SAGA_STEP_NUMBER    INTEGER                             NOT NULL,
    SAGA_EVENT_RESPONSE BLOB,
    CREATE_USER         VARCHAR2(32)                        NOT NULL,
    CREATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER         VARCHAR2(32)                        NOT NULL,
    UPDATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SAGA_EVENT_STATES_PK PRIMARY KEY (SAGA_EVENT_ID)
) TABLESPACE API_PEN_BLOB_DATA;
ALTER TABLE SAGA_EVENT_STATES
    ADD CONSTRAINT SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES SAGA (SAGA_ID);
CREATE INDEX SAGA_EVENT_STATES_SAGA_ID_IDX ON SAGA_EVENT_STATES (SAGA_ID) TABLESPACE API_PEN_IDX;

