ALTER TABLE PEN_REPLICATION_EVENT
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE PEN_REPLICATION_EVENT
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE PEN_REPLICATION_SAGA
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE PEN_REPLICATION_SAGA
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE PEN_REPLICATION_SAGA_EVENT_STATES
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE PEN_REPLICATION_SAGA_EVENT_STATES
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

