package ca.bc.gov.educ.api.pen.replication.mappers;

import ca.bc.gov.educ.api.pen.replication.model.TraxStudentEntity;
import ca.bc.gov.educ.api.pen.replication.struct.StudentAddress;
import ca.bc.gov.educ.api.pen.replication.struct.StudentUpdate;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.factory.Mappers;

@Mapper(uses = {LocalDateTimeMapper.class, StringMapper.class})
public interface TraxStudentMapper {

  TraxStudentMapper mapper = Mappers.getMapper(TraxStudentMapper.class);
  
  @Mapping(target = "studNo", ignore = true)
  @Mapping(target = "archiveFlag", ignore = true)
  @Mapping(target = "address1", ignore = true)
  @Mapping(target = "address2", ignore = true)
  @Mapping(target = "city", ignore = true)
  @Mapping(target = "provCode", ignore = true)
  @Mapping(target = "cntryCode", ignore = true)
  @Mapping(target = "postal", ignore = true)
  @Mapping(target = "studCitiz", ignore = true)
  @Mapping(target = "studGrade", ignore = true)
  @Mapping(target = "mincode", ignore = true)
  @Mapping(target = "studSin", ignore = true)
  @Mapping(target = "prgmCode", ignore = true)
  @Mapping(target = "prgmCode2", ignore = true)
  @Mapping(target = "prgmCode3", ignore = true)
  @Mapping(target = "studPsiPermit", ignore = true)
  @Mapping(target = "studRsrchPermit", ignore = true)
  @Mapping(target = "studStatus", ignore = true)
  @Mapping(target = "studConsedFlag", ignore = true)
  @Mapping(target = "yrEnter11", ignore = true)
  @Mapping(target = "gradDate", ignore = true)
  @Mapping(target = "dogwoodFlag", ignore = true)
  @Mapping(target = "honourFlag", ignore = true)
  @Mapping(target = "mincodeGrad", ignore = true)
  @Mapping(target = "frenchDogwood", ignore = true)
  @Mapping(target = "prgmCode4", ignore = true)
  @Mapping(target = "prgmCode5", ignore = true)
  @Mapping(target = "sccDate", ignore = true)
  @Mapping(target = "gradReqtYear", ignore = true)
  @Mapping(target = "slpDate", ignore = true)
  @Mapping(target = "mergedFromPen", ignore = true)
  @Mapping(target = "gradReqtYearAtGrad", ignore = true)
  @Mapping(target = "studGradeAtGrad", ignore = true)
  @Mapping(target = "xcriptActvDate", ignore = true)
  @Mapping(target = "allowedAdult", ignore = true)
  @Mapping(target = "ssaNominationDate", ignore = true)
  @Mapping(target = "adjTestYear", ignore = true)
  @Mapping(target = "graduatedAdult", ignore = true)
  @Mapping(target = "supplierNo", ignore = true)
  @Mapping(target = "siteNo", ignore = true)
  @Mapping(target = "emailAddress", ignore = true)
  @Mapping(target = "englishCert", ignore = true)
  @Mapping(target = "frenchCert", ignore = true)
  @Mapping(target = "englishCertDate", ignore = true)
  @Mapping(target = "frenchCertDate", ignore = true)
  @Mapping(source = "legalLastName", target = "studSurname")
  @Mapping(source = "legalFirstName", target = "studGiven")
  @Mapping(source = "legalMiddleNames", target = "studMiddle")
  @Mapping(source = "dob", target = "studBirth")
  @Mapping(source = "sexCode", target = "studSex")
  @Mapping(source = "localID", target = "studLocalId")
  @Mapping(target = "trueStudentID", ignore = true)
  TraxStudentEntity toTraxStudent(StudentUpdate studentUpdate);

  @Mapping(target = "studNo", ignore = true)
  @Mapping(target = "archiveFlag", ignore = true)
  @Mapping(source = "addressLine1", target = "address1")
  @Mapping(source = "addressLine2", target = "address2")
  @Mapping(source = "city", target = "city")
  @Mapping(source = "provinceStateCode", target = "provCode")
  @Mapping(source = "countryCode", target = "cntryCode")
  @Mapping(source = "postalZip", target = "postal")
  @Mapping(target = "studCitiz", ignore = true)
  @Mapping(target = "studGrade", ignore = true)
  @Mapping(target = "mincode", ignore = true)
  @Mapping(target = "studSin", ignore = true)
  @Mapping(target = "prgmCode", ignore = true)
  @Mapping(target = "prgmCode2", ignore = true)
  @Mapping(target = "prgmCode3", ignore = true)
  @Mapping(target = "studPsiPermit", ignore = true)
  @Mapping(target = "studRsrchPermit", ignore = true)
  @Mapping(target = "studStatus", ignore = true)
  @Mapping(target = "studConsedFlag", ignore = true)
  @Mapping(target = "yrEnter11", ignore = true)
  @Mapping(target = "gradDate", ignore = true)
  @Mapping(target = "dogwoodFlag", ignore = true)
  @Mapping(target = "honourFlag", ignore = true)
  @Mapping(target = "mincodeGrad", ignore = true)
  @Mapping(target = "frenchDogwood", ignore = true)
  @Mapping(target = "prgmCode4", ignore = true)
  @Mapping(target = "prgmCode5", ignore = true)
  @Mapping(target = "sccDate", ignore = true)
  @Mapping(target = "gradReqtYear", ignore = true)
  @Mapping(target = "slpDate", ignore = true)
  @Mapping(target = "mergedFromPen", ignore = true)
  @Mapping(target = "gradReqtYearAtGrad", ignore = true)
  @Mapping(target = "studGradeAtGrad", ignore = true)
  @Mapping(target = "xcriptActvDate", ignore = true)
  @Mapping(target = "allowedAdult", ignore = true)
  @Mapping(target = "ssaNominationDate", ignore = true)
  @Mapping(target = "adjTestYear", ignore = true)
  @Mapping(target = "graduatedAdult", ignore = true)
  @Mapping(target = "supplierNo", ignore = true)
  @Mapping(target = "siteNo", ignore = true)
  @Mapping(target = "emailAddress", ignore = true)
  @Mapping(target = "englishCert", ignore = true)
  @Mapping(target = "frenchCert", ignore = true)
  @Mapping(target = "englishCertDate", ignore = true)
  @Mapping(target = "frenchCertDate", ignore = true)
  @Mapping(target = "legalLastName", ignore = true)
  @Mapping(target = "legalFirstName", ignore = true)
  @Mapping(target = "legalMiddleNames", ignore = true)
  @Mapping(target = "dob", ignore = true)
  @Mapping(target = "sexCode", ignore = true)
  @Mapping(target = "localID", ignore = true)
  @Mapping(target = "trueStudentID", ignore = true)
  TraxStudentEntity toTraxStudent(StudentAddress studentAddress);
  
  @Mapping(target = "studNo", ignore = true)
  @Mapping(target = "archiveFlag", ignore = true)
  @Mapping(target = "address1", ignore = true)
  @Mapping(target = "address2", ignore = true)
  @Mapping(target = "city", ignore = true)
  @Mapping(target = "provCode", ignore = true)
  @Mapping(target = "cntryCode", ignore = true)
  @Mapping(target = "postal", ignore = true)
  @Mapping(target = "studCitiz", ignore = true)
  @Mapping(target = "studGrade", ignore = true)
  @Mapping(target = "mincode", ignore = true)
  @Mapping(target = "studSin", ignore = true)
  @Mapping(target = "prgmCode", ignore = true)
  @Mapping(target = "prgmCode2", ignore = true)
  @Mapping(target = "prgmCode3", ignore = true)
  @Mapping(target = "studPsiPermit", ignore = true)
  @Mapping(target = "studRsrchPermit", ignore = true)
  @Mapping(target = "studStatus", ignore = true)
  @Mapping(target = "studConsedFlag", ignore = true)
  @Mapping(target = "yrEnter11", ignore = true)
  @Mapping(target = "gradDate", ignore = true)
  @Mapping(target = "dogwoodFlag", ignore = true)
  @Mapping(target = "honourFlag", ignore = true)
  @Mapping(target = "mincodeGrad", ignore = true)
  @Mapping(target = "frenchDogwood", ignore = true)
  @Mapping(target = "prgmCode4", ignore = true)
  @Mapping(target = "prgmCode5", ignore = true)
  @Mapping(target = "sccDate", ignore = true)
  @Mapping(target = "gradReqtYear", ignore = true)
  @Mapping(target = "slpDate", ignore = true)
  @Mapping(target = "mergedFromPen", ignore = true)
  @Mapping(target = "gradReqtYearAtGrad", ignore = true)
  @Mapping(target = "studGradeAtGrad", ignore = true)
  @Mapping(target = "xcriptActvDate", ignore = true)
  @Mapping(target = "allowedAdult", ignore = true)
  @Mapping(target = "ssaNominationDate", ignore = true)
  @Mapping(target = "adjTestYear", ignore = true)
  @Mapping(target = "graduatedAdult", ignore = true)
  @Mapping(target = "supplierNo", ignore = true)
  @Mapping(target = "siteNo", ignore = true)
  @Mapping(target = "emailAddress", ignore = true)
  @Mapping(target = "englishCert", ignore = true)
  @Mapping(target = "frenchCert", ignore = true)
  @Mapping(target = "englishCertDate", ignore = true)
  @Mapping(target = "frenchCertDate", ignore = true)
  void updateTraxStudent(TraxStudentEntity traxStudentEntity, @MappingTarget TraxStudentEntity targetEntity);


}
